FROM flink:1.17.0-scala_2.12

USER root

# Install python3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Install PyFlink and your dependencies
RUN pip3 install --no-cache-dir apache-flink==1.17.0 pymongo requests kafka-python confluent-kafka python-dateutil flask

# Set python as default
ENV PYTHON_EXECUTABLE=python3

WORKDIR /opt/flink/etl_app

# Copy your app code
COPY ./src ./src
COPY ./config ./config

