version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  etl-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl-producer
    depends_on:
      - kafka
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /opt/flink/etl_app
    command: ["python", "producer.py"]
    volumes:
      - .:/opt/flink/etl_app

  etl-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl-consumer
    depends_on:
      - kafka
      - mongo
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /opt/flink/etl_app
    command: ["python", "src/consumer.py"]
    volumes:
      - .:/opt/flink/etl_app

volumes:
  mongo-data:
  mongo-config:
