services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"

  config_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config_client
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    working_dir: /opt/flink/etl_app
    volumes:
      - .:/opt/flink/etl_app

  flink-jobmanager:
    image: flink:1.17.0-python
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    volumes:
      - .:/opt/flink/etl_app

volumes:
  mongo-data:
  mongo-config:
